-- Create customers table
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT UNIQUE NOT NULL,
    email TEXT,
    default_address TEXT,
    default_lat DOUBLE PRECISION,
    default_lng DOUBLE PRECISION,
    default_colony TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Ensure orders table exists with all necessary fields
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT REFERENCES places(id),
    customer_id BIGINT REFERENCES customers(id), -- Optional: if you want to link them
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    delivery_address TEXT,
    delivery_lat DOUBLE PRECISION,
    delivery_lng DOUBLE PRECISION,
    delivery_colony TEXT,
    shipping_zone_id BIGINT REFERENCES shipping_zones(id),
    delivery_price DECIMAL(10,2) DEFAULT 0,
    items JSONB NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS (Optional, but recommended)
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (adjust as needed for security)
CREATE POLICY "Allow public insert to customers" ON customers FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select to customers" ON customers FOR SELECT USING (true);
CREATE POLICY "Allow public update to customers" ON customers FOR UPDATE USING (true);

CREATE POLICY "Allow public insert to orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select to orders" ON orders FOR SELECT USING (true);
CREATE POLICY "Allow public update to orders" ON orders FOR UPDATE USING (true);
