-- Insertar municipios de Nuevo León (state_id: 19)
-- Basado en los municipios más comunes y de mayor actividad
INSERT INTO municipalities (state_id, name, slug) VALUES
(19, 'Abasolo', 'abasolo'),
(19, 'Agualeguas', 'agualeguas'),
(19, 'Allende', 'allende'),
(19, 'Anáhuac', 'anahuac'),
(19, 'Apodaca', 'apodaca'),
(19, 'Aramberri', 'aramberri'),
(19, 'Bustamante', 'bustamante'),
(19, 'Cadereyta Jiménez', 'cadereyta-jimenez'),
(19, 'Carmen', 'el-carmen'),
(19, 'Cerralvo', 'cerralvo'),
(19, 'China', 'china'),
(19, 'Ciénega de Flores', 'cienega-de-flores'),
(19, 'Doctor Arroyo', 'doctor-arroyo'),
(19, 'Doctor Coss', 'doctor-coss'),
(19, 'Doctor González', 'doctor-gonzalez'),
(19, 'Galeana', 'galeana'),
(19, 'García', 'garcia'),
(19, 'General Bravo', 'general-bravo'),
(19, 'General Escobedo', 'general-escobedo'),
(19, 'General Terán', 'general-teran'),
(19, 'General Treviño', 'general-treviño'),
(19, 'General Zaragoza', 'general-zaragoza'),
(19, 'General Zuazua', 'general-zuazua'),
(19, 'Guadalupe', 'guadalupe'),
(19, 'Hidalgo', 'hidalgo'),
(19, 'Higueras', 'higueras'),
(19, 'Hualahuises', 'hualahuises'),
(19, 'Iturbide', 'iturbide'),
(19, 'Juárez', 'juarez'),
(19, 'Lampazos de Naranjo', 'lampazos-de-naranjo'),
(19, 'Linares', 'linares'),
(19, 'Los Aldamas', 'los-aldamas'),
(19, 'Los Herreras', 'los-herreras'),
(19, 'Los Ramones', 'los-ramones'),
(19, 'Marín', 'marin'),
(19, 'Melchor Ocampo', 'melchor-ocampo'),
(19, 'Mier y Noriega', 'mier-y-noriega'),
(19, 'Mina', 'mina'),
(19, 'Montemorelos', 'montemorelos'),
(19, 'Monterrey', 'monterrey'),
(19, 'Parás', 'paras'),
(19, 'Pesquería', 'pesqueria'),
(19, 'Rayones', 'rayones'),
(19, 'Sabinas Hidalgo', 'sabinas-hidalgo'),
(19, 'Salinas Victoria', 'salinas-victoria'),
(19, 'San Nicolás de los Garza', 'san-nicolas-de-los-garza'),
(19, 'San Pedro Garza García', 'san-pedro-garza-garcia'),
(19, 'Santa Catarina', 'santa-catarina'),
(19, 'Santiago', 'santiago'),
(19, 'Vallecillo', 'vallecillo'),
(19, 'Villaldama', 'villaldama')
ON CONFLICT DO NOTHING;
